---
title: "About me"
author: 
date: 
output: html_document
---

I am a lecturer in Mathematical Data Science at the [School of Mathematics](https://www.maths.ed.ac.uk/) and [Edinburgh Futures Institute](https://efi.ed.ac.uk/) at the University of Edinburgh. I joined the School of Mathematics as a University Teacher in Statistics in September 2017. Previously, I completed my PhD in Statistics at the University of St Andrews, under the supervision of Michail Papathomas and Ruth King, working on identifiability and parameter redundancy of log-linear models fitted to sparse contingency tables.


$~$


### Research Interests

- Parameter redundancy
- Identifiability problem in statistical models
- Multiple systems estimation
- Applications of Statistics in Social Sciences and Psychology
- Statistics and Data Science pedagogy

$~$

### Education Background

-  PhD in Statistics, University of St Andrews, 2013-17
-  MSc in Mathematical Statistics, University of Tabriz, 2009-11
-  BSc in Statistics, University of Tabriz, 2005-09


$~$

### Contact

Dr. Serveh Sharifi Far (_she/her_)

Lecturer in Mathematical Data Science

University of Edinburgh


Address: Office 5313- School of Mathematics- 
University of Edinburgh- James Clerk Maxwell Building- Peter Guthrie Tait Road- Edinburgh- EH9 3FD


Email: serveh.sharifi@ed.ac.uk

